Use healthcare_management_system;

-- Calculate total revenue generated by each hospital
SELECT 
    h.name AS HospitalCLinic, SUM(b.cost) AS TotalRevenue
FROM
    HospitalClinic h
        JOIN
    billing b ON h.HospitalClinicID = b.HospitalClinicID
GROUP BY h.name
ORDER BY TotalRevenue;

-- Identify patients with most recent medical visits
SELECT 
    m.PatientID,
    CONCAT(p.FirstName, ' ', p.LastName) AS PatientName,
    MAX(m.DateOfVisit) AS RecentVisitDate
FROM
    MedicalRecord m
        JOIN
    Patient p ON m.PatientID = p.PatientID
GROUP BY m.PatientID , PatientName
ORDER BY RecentVisitDate DESC;

-- How many patients are covered by each insurance provider?
SELECT 
    i.Full_Name AS InsuranceProvider,
    COUNT(p.PatientID) AS TotalPatients
FROM
    insurance i
        LEFT JOIN
    patient p ON i.InsuranceID = p.InsuranceID
GROUP BY i.Full_Name;

-- What is the total medical cost covered by each insurance provider
SELECT 
    h.Name AS InsuranceProvider, SUM(b.cost) AS TotalRevenue
FROM
    HospitalClinic h
        JOIN
    billing b ON h.HospitalClinicID = b.HospitalClinicID
GROUP BY h.name
ORDER BY TotalRevenue
